/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutVehiclesIndexRouteImport } from './routes/_layout/vehicles/index'
import { Route as LayoutTransportsIndexRouteImport } from './routes/_layout/transports/index'
import { Route as LayoutStarshipsIndexRouteImport } from './routes/_layout/starships/index'
import { Route as LayoutSpeciesIndexRouteImport } from './routes/_layout/species/index'
import { Route as LayoutPlanetsIndexRouteImport } from './routes/_layout/planets/index'
import { Route as LayoutFilmsIndexRouteImport } from './routes/_layout/films/index'
import { Route as LayoutCharactersIndexRouteImport } from './routes/_layout/characters/index'
import { Route as LayoutVehiclesVehicleIdRouteImport } from './routes/_layout/vehicles/$vehicleId'
import { Route as LayoutStarshipsStarshipIdRouteImport } from './routes/_layout/starships/$starshipId'
import { Route as LayoutSpeciesSpeciesIdRouteImport } from './routes/_layout/species/$speciesId'
import { Route as LayoutPlanetsPlanetIdRouteImport } from './routes/_layout/planets/$planetId'
import { Route as LayoutFilmsFilmIdRouteImport } from './routes/_layout/films/$filmId'
import { Route as LayoutCharactersCharacterIdRouteImport } from './routes/_layout/characters/$characterId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVehiclesIndexRoute = LayoutVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransportsIndexRoute = LayoutTransportsIndexRouteImport.update({
  id: '/transports/',
  path: '/transports/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStarshipsIndexRoute = LayoutStarshipsIndexRouteImport.update({
  id: '/starships/',
  path: '/starships/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSpeciesIndexRoute = LayoutSpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlanetsIndexRoute = LayoutPlanetsIndexRouteImport.update({
  id: '/planets/',
  path: '/planets/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilmsIndexRoute = LayoutFilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCharactersIndexRoute = LayoutCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVehiclesVehicleIdRoute = LayoutVehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStarshipsStarshipIdRoute =
  LayoutStarshipsStarshipIdRouteImport.update({
    id: '/starships/$starshipId',
    path: '/starships/$starshipId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSpeciesSpeciesIdRoute = LayoutSpeciesSpeciesIdRouteImport.update({
  id: '/species/$speciesId',
  path: '/species/$speciesId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlanetsPlanetIdRoute = LayoutPlanetsPlanetIdRouteImport.update({
  id: '/planets/$planetId',
  path: '/planets/$planetId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilmsFilmIdRoute = LayoutFilmsFilmIdRouteImport.update({
  id: '/films/$filmId',
  path: '/films/$filmId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCharactersCharacterIdRoute =
  LayoutCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/characters/$characterId': typeof LayoutCharactersCharacterIdRoute
  '/films/$filmId': typeof LayoutFilmsFilmIdRoute
  '/planets/$planetId': typeof LayoutPlanetsPlanetIdRoute
  '/species/$speciesId': typeof LayoutSpeciesSpeciesIdRoute
  '/starships/$starshipId': typeof LayoutStarshipsStarshipIdRoute
  '/vehicles/$vehicleId': typeof LayoutVehiclesVehicleIdRoute
  '/characters/': typeof LayoutCharactersIndexRoute
  '/films/': typeof LayoutFilmsIndexRoute
  '/planets/': typeof LayoutPlanetsIndexRoute
  '/species/': typeof LayoutSpeciesIndexRoute
  '/starships/': typeof LayoutStarshipsIndexRoute
  '/transports/': typeof LayoutTransportsIndexRoute
  '/vehicles/': typeof LayoutVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/characters/$characterId': typeof LayoutCharactersCharacterIdRoute
  '/films/$filmId': typeof LayoutFilmsFilmIdRoute
  '/planets/$planetId': typeof LayoutPlanetsPlanetIdRoute
  '/species/$speciesId': typeof LayoutSpeciesSpeciesIdRoute
  '/starships/$starshipId': typeof LayoutStarshipsStarshipIdRoute
  '/vehicles/$vehicleId': typeof LayoutVehiclesVehicleIdRoute
  '/characters': typeof LayoutCharactersIndexRoute
  '/films': typeof LayoutFilmsIndexRoute
  '/planets': typeof LayoutPlanetsIndexRoute
  '/species': typeof LayoutSpeciesIndexRoute
  '/starships': typeof LayoutStarshipsIndexRoute
  '/transports': typeof LayoutTransportsIndexRoute
  '/vehicles': typeof LayoutVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/characters/$characterId': typeof LayoutCharactersCharacterIdRoute
  '/_layout/films/$filmId': typeof LayoutFilmsFilmIdRoute
  '/_layout/planets/$planetId': typeof LayoutPlanetsPlanetIdRoute
  '/_layout/species/$speciesId': typeof LayoutSpeciesSpeciesIdRoute
  '/_layout/starships/$starshipId': typeof LayoutStarshipsStarshipIdRoute
  '/_layout/vehicles/$vehicleId': typeof LayoutVehiclesVehicleIdRoute
  '/_layout/characters/': typeof LayoutCharactersIndexRoute
  '/_layout/films/': typeof LayoutFilmsIndexRoute
  '/_layout/planets/': typeof LayoutPlanetsIndexRoute
  '/_layout/species/': typeof LayoutSpeciesIndexRoute
  '/_layout/starships/': typeof LayoutStarshipsIndexRoute
  '/_layout/transports/': typeof LayoutTransportsIndexRoute
  '/_layout/vehicles/': typeof LayoutVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/$characterId'
    | '/films/$filmId'
    | '/planets/$planetId'
    | '/species/$speciesId'
    | '/starships/$starshipId'
    | '/vehicles/$vehicleId'
    | '/characters/'
    | '/films/'
    | '/planets/'
    | '/species/'
    | '/starships/'
    | '/transports/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/$characterId'
    | '/films/$filmId'
    | '/planets/$planetId'
    | '/species/$speciesId'
    | '/starships/$starshipId'
    | '/vehicles/$vehicleId'
    | '/characters'
    | '/films'
    | '/planets'
    | '/species'
    | '/starships'
    | '/transports'
    | '/vehicles'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/characters/$characterId'
    | '/_layout/films/$filmId'
    | '/_layout/planets/$planetId'
    | '/_layout/species/$speciesId'
    | '/_layout/starships/$starshipId'
    | '/_layout/vehicles/$vehicleId'
    | '/_layout/characters/'
    | '/_layout/films/'
    | '/_layout/planets/'
    | '/_layout/species/'
    | '/_layout/starships/'
    | '/_layout/transports/'
    | '/_layout/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vehicles/': {
      id: '/_layout/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof LayoutVehiclesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transports/': {
      id: '/_layout/transports/'
      path: '/transports'
      fullPath: '/transports/'
      preLoaderRoute: typeof LayoutTransportsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/starships/': {
      id: '/_layout/starships/'
      path: '/starships'
      fullPath: '/starships/'
      preLoaderRoute: typeof LayoutStarshipsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/species/': {
      id: '/_layout/species/'
      path: '/species'
      fullPath: '/species/'
      preLoaderRoute: typeof LayoutSpeciesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/planets/': {
      id: '/_layout/planets/'
      path: '/planets'
      fullPath: '/planets/'
      preLoaderRoute: typeof LayoutPlanetsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/films/': {
      id: '/_layout/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof LayoutFilmsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/characters/': {
      id: '/_layout/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof LayoutCharactersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vehicles/$vehicleId': {
      id: '/_layout/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof LayoutVehiclesVehicleIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/starships/$starshipId': {
      id: '/_layout/starships/$starshipId'
      path: '/starships/$starshipId'
      fullPath: '/starships/$starshipId'
      preLoaderRoute: typeof LayoutStarshipsStarshipIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/species/$speciesId': {
      id: '/_layout/species/$speciesId'
      path: '/species/$speciesId'
      fullPath: '/species/$speciesId'
      preLoaderRoute: typeof LayoutSpeciesSpeciesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/planets/$planetId': {
      id: '/_layout/planets/$planetId'
      path: '/planets/$planetId'
      fullPath: '/planets/$planetId'
      preLoaderRoute: typeof LayoutPlanetsPlanetIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/films/$filmId': {
      id: '/_layout/films/$filmId'
      path: '/films/$filmId'
      fullPath: '/films/$filmId'
      preLoaderRoute: typeof LayoutFilmsFilmIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/characters/$characterId': {
      id: '/_layout/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof LayoutCharactersCharacterIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCharactersCharacterIdRoute: typeof LayoutCharactersCharacterIdRoute
  LayoutFilmsFilmIdRoute: typeof LayoutFilmsFilmIdRoute
  LayoutPlanetsPlanetIdRoute: typeof LayoutPlanetsPlanetIdRoute
  LayoutSpeciesSpeciesIdRoute: typeof LayoutSpeciesSpeciesIdRoute
  LayoutStarshipsStarshipIdRoute: typeof LayoutStarshipsStarshipIdRoute
  LayoutVehiclesVehicleIdRoute: typeof LayoutVehiclesVehicleIdRoute
  LayoutCharactersIndexRoute: typeof LayoutCharactersIndexRoute
  LayoutFilmsIndexRoute: typeof LayoutFilmsIndexRoute
  LayoutPlanetsIndexRoute: typeof LayoutPlanetsIndexRoute
  LayoutSpeciesIndexRoute: typeof LayoutSpeciesIndexRoute
  LayoutStarshipsIndexRoute: typeof LayoutStarshipsIndexRoute
  LayoutTransportsIndexRoute: typeof LayoutTransportsIndexRoute
  LayoutVehiclesIndexRoute: typeof LayoutVehiclesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCharactersCharacterIdRoute: LayoutCharactersCharacterIdRoute,
  LayoutFilmsFilmIdRoute: LayoutFilmsFilmIdRoute,
  LayoutPlanetsPlanetIdRoute: LayoutPlanetsPlanetIdRoute,
  LayoutSpeciesSpeciesIdRoute: LayoutSpeciesSpeciesIdRoute,
  LayoutStarshipsStarshipIdRoute: LayoutStarshipsStarshipIdRoute,
  LayoutVehiclesVehicleIdRoute: LayoutVehiclesVehicleIdRoute,
  LayoutCharactersIndexRoute: LayoutCharactersIndexRoute,
  LayoutFilmsIndexRoute: LayoutFilmsIndexRoute,
  LayoutPlanetsIndexRoute: LayoutPlanetsIndexRoute,
  LayoutSpeciesIndexRoute: LayoutSpeciesIndexRoute,
  LayoutStarshipsIndexRoute: LayoutStarshipsIndexRoute,
  LayoutTransportsIndexRoute: LayoutTransportsIndexRoute,
  LayoutVehiclesIndexRoute: LayoutVehiclesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
